sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

git:
  submodules: false

before_script:
- chmod +x gradlew
install: ./gradlew setupDecompWorkspace
script: ./gradlew build

notifications:
  email: false