sudo: required
dist: trusty

language: java

before_script:
- chmod +x gradlew
before_install:
 - chmod +x gradlew 
 
jdk:
  - openjdk8
  - oraclejdk8

git:
  submodules: false


install: ./gradlew setupDecompWorkspace
script: ./gradlew build

notifications:
  email: false